"""Symbol-to-speech mapping for code reading."""

SYMBOL_MAP = {
    '.': ' dot ',
    ',': ' comma ',
    ':': ' colon ',
    ';': ' semicolon ',
    '(': ' open paren ',
    ')': ' close paren ',
    '[': ' open bracket ',
    ']': ' close bracket ',
    '{': ' open brace ',
    '}': ' close brace ',
    '<': ' less than ',
    '>': ' greater than ',
    '=': ' equals ',
    '==': ' double equals ',
    '!=': ' not equals ',
    '===': ' triple equals ',
    '!==': ' not triple equals ',
    '+=': ' plus equals ',
    '-=': ' minus equals ',
    '*=': ' star equals ',
    '/=': ' slash equals ',
    '=>': ' arrow ',
    '->': ' arrow ',
    '<=': ' less than or equal ',
    '>=': ' greater than or equal ',
    '+': ' plus ',
    '-': ' hyphen ',
    '*': ' star ',
    '/': ' slash ',
    '\\': ' backslash ',
    '|': ' pipe ',
    '||': ' double pipe ',
    '&&': ' double ampersand ',
    '&': ' ampersand ',
    '!': ' exclamation ',
    '?': ' question mark ',
    '@': ' at ',
    '#': ' hash ',
    '$': ' dollar ',
    '%': ' percent ',
    '^': ' caret ',
    '~': ' tilde ',
    '_': ' underscore ',
    '`': ' backtick ',
    '"': ' quote ',
    "'": ' single quote ',
    '...': ' dot dot dot ',
    '//': ' double slash ',
    '/*': ' slash star ',
    '*/': ' star slash ',
}

# Sort by length (longest first) so multi-char symbols match before single-char
SORTED_SYMBOLS = sorted(SYMBOL_MAP.keys(), key=len, reverse=True)
